FROM python:3.11-slim

WORKDIR /app
COPY services/api/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY worker /app/worker
COPY services/api /app/services_api

ENV PYTHONUNBUFFERED=1
WORKDIR /app/worker
CMD ["python", "worker.py"]
